name: caferat_app
description: "Rating app for cafe around East Java"

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  bloc: ^9.0.0
  bloc_concurrency: ^0.3.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  fluttertoast: ^8.2.12
  font_awesome_flutter: ^10.8.0
  form_field_validator: ^1.1.0
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  go_router: ^15.1.3
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.3
  supabase_flutter: ^2.9.1

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.15
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  mockito: ^5.4.4
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
